### ISSUE TITLE
Android 9/Lineage 16

### ISSUE THREAD

**Issue by dragonBall561** [ggow/android_device_amazon_mustang#3]
On the fire 7 2019, the fireOS 7 (Android 9 based) is out with a Kernel source available. Is it possible to have an Android 9 device tree for this device? Is there any way I could help?

**Comment by ggow** [comment]
Yes, check here:
https://forum.xda-developers.com/t/rom-testing-mustang-lineage-16-0-15-feb-2021.4234211/#post-84510443

This uses fireos 7 kernel and blobs.

Feel free test, download repos etc, on the 3rd post of the the thread there is a todo list
